### ISSUE TITLE
Route not found returns grpc unknown error type instead of not found error type

### ISSUE THREAD

**Issue by autocracy** [pomerium/enterprise-client#46]
Getting GRPC UNKNOWN / "sql: no rows in result set" but should be getting GRPC NOT_FOUND. I think I'll have a few more as I wrap up building out this Terraform provider (GRPC equivalent of returning HTTP/500 instead of HTTP/404)

Replication: read route request on a missing / deleted id. Get error with code of, expect code of 5. https://grpc.github.io/grpc/core/md_doc_statuscodes.html

**Comment by calebdoxsey** [comment]
This should be fixed in the next version of the enterprise console.
